### ISSUE TITLE
关于订阅内容列表已读未读的一点小建议

### ISSUE THREAD

**Issue by lan5635** [RSSxdev/Readdig#1]
GitHub已star！
目前未读项是这样展示的
![image](https://user-images.githubusercontent.com/10723912/162871906-cd710e99-1f0f-492c-b29c-cad13add3072.png)
已读项是这样展示的
![image](https://user-images.githubusercontent.com/10723912/162871963-8b2d3a2e-dd31-446a-a68b-53f98020e1a1.png)
区别是已读项不显示小绿点
如果已读项的标题能够不加粗就更好啦！

鞠躬！

**Comment by RSSxdev** [comment]
已加入计划中。
后面会把标题改成灰色，并会增加过滤已读的。

**Comment by RSSxdev** [comment]
已增加。
请清空浏览器缓存更新查看，另在设置中可以打开过滤已读。
