### ISSUE TITLE
关于手机适配的一个小建议

### ISSUE THREAD

**Issue by bu1** [RSSxdev/Readdig#2]
用手机阅读时最左边的列表是否可以增加一个悬浮按钮来设置全部隐藏？手机是窄屏幕，左边一直显示的话会占用空间，视觉上特别不习惯。

提一个可能是BUG的问题，从蚁阅导出带分组的opml文件导入到readdig会导致分组丢失。

**Comment by RSSxdev** [comment]
左边列表是为了和电脑保持一致，不过我自己还是满喜欢的，可以快速选择。后面我看能不能增加设置。
蚁阅的 OPML 文件我也没看过格式是什么样的，有时间我测试一下。

**Comment by bu1** [comment]
还是关于导入opml文件的问题，导入后分组下的订阅源会丢失，与文件内容的数量不符。
测试了如下链接：
`https://github.com/zlexdl/mirror/blob/main/Inoreader%20Feeds%2020220316.xml`
很多分组下会缺少订阅源，猜测可能是一次性导入太多，处理不过来，拆分后再次导入结果与整体导入一致，会有订阅源缺失。
把缺失的订阅源通过手工单URL添加，成功添加，但是通过opml文件批量添加依旧会缺失。

最后，感谢大神开发这么优秀的应用！

**Comment by bu1** [comment]
> 左边列表是为了和电脑保持一致，不过我自己还是满喜欢的，可以快速选择。后面我看能不能增加设置。 蚁阅的 OPML 文件我也没看过格式是什么样的，有时间我测试一下。



> 还是关于导入opml文件的问题，导入后分组下的订阅源会丢失，与文件内容的数量不符。 测试了如下链接： `https://github.com/zlexdl/mirror/blob/main/Inoreader%20Feeds%2020220316.xml` 很多分组下会缺少订阅源，猜测可能是一次性导入太多，处理不过来，拆分后再次导入结果与整体导入一致，会有订阅源缺失。 把缺失的订阅源通过手工单URL添加，成功添加，但是通过opml文件批量添加依旧会缺失。
> 
> 最后，感谢大神开发这么优秀的应用！

opml文件中大部分无法导入的域名是submirror

**Comment by RSSxdev** [comment]
你提供的 OPML 里面有很多源是重复的，一条源存在于多个目录下。我这边是不支持一条源存在于多个目录，由于添加的时候没有过滤重复的所以出错了，我需要修改一下过滤掉重复的。

**Comment by bu1** [comment]
一个小BUG，通过获取原文的方式读取到的原文内容如果存在代码段，代码段会乱码。

**Comment by RSSxdev** [comment]
> 一个小BUG，通过获取原文的方式读取到的原文内容如果存在代码段，代码段会乱码。

是否可以提供一个文章链接我测试一下。

**Comment by RSSxdev** [comment]
已在偏好设置里面增加了一个“移动设备隐藏边栏”。
OPML 的问题在导入的时候已增加处理重复数据。
代码段会乱码 已修改样式处理，可能部分还会有问题。

需要清空浏览器缓存或重新添加到主屏来快速更新应用或者等待自动更新（比较慢）。

如果有其它问题可以在开新的 issue
