### ISSUE TITLE
关于OPML文件导入丢失订阅问题与代码段乱码问题反馈

### ISSUE THREAD

**Issue by bu1** [RSSxdev/Readdig#3]
感谢大神耗费精力维护这个项目，最近一段时间测试过很多RSS软件，这个是目前用起来最舒服的。

1. 关于代码段乱码问题
目前看了十几个FEED的文章，没有乱码问题了

2. opml文件导入问题
上次提供了一个OPML文件，这边再次测试了，还是会有上次那个问题(已更新到最新版本，也换浏览器尝试过)。
`https://github.com/zlexdl/mirror/blob/main/Inoreader%20Feeds%2020220316.xml`
比如在日记分类下，所有无重复订阅源都无法自动导入，手动添加没有问题。

ps：本来想通过脚本的方式请求手动添加的API批量导入，但是返回的数据好像加密过？都是乱码的...放弃了

**Comment by RSSxdev** [comment]
opml 导入问题我在测试一下。
api 是没有加密的，只需要在请求头加上 authorization （为用户的 jwt 值）。

**Comment by bu1** [comment]
感谢，又看了一遍，是我没有处理好编码导致的乱码问题。
重新导入了，有一个ssr无法被正确识别，返回"We couldn't find that feed URL. "，url如下：
`https://www.chainfeeds.xyz/rss'`
测试过别的软件是可以正常导入的~

**Comment by RSSxdev** [comment]
`https://www.chainfeeds.xyz/rss`
这条订阅源不够规范，在源信息里面缺少必须的字段 link，导致验证不通过。已修改代码处理这个问题。

OPML 的问题已再次修改，请再次尝试，谢谢。

**Comment by bu1** [comment]
已测试，无误。:sparkles:
