### ISSUE TITLE
关于英文句尾截断与阅读页搜索栏隐藏的小建议

### ISSUE THREAD

**Issue by bu1** [RSSxdev/Readdig#4]
经过这段时间的体验，再提两个(可能是)改进的小建议：

a）.英文是否可以不截断

如图所示，目前句子尾部的英文存在截断问题

![](https://s3.bmp.ovh/imgs/2022/06/27/bfe443585bff46ae.png)

b）.搜索栏隐藏

在阅读页面时搜索栏会常驻顶部，是否可以替换常驻顶部的组件呢？换成下面这个可能更符合习惯操作(下图所示)。理由如下：

1. 进入阅读页面后基本上用不到搜索栏
2. 下面这个组件常驻后，读到一半想要收藏可以直接点击收藏，而不必再上滑到最上面。
3. 下面这个组件常驻后，读完后可以直接点击切换下(上)一篇文章，而不必再上滑到最上面。
4. 同理，分享按钮也是如此。

![](https://s3.bmp.ovh/imgs/2022/06/27/4ff83c1eb28c0213.png)

> 截这个图的时候不是最新版。

**Comment by bu1** [comment]
给一个布局参考建议
![](https://s3.bmp.ovh/imgs/2022/06/27/b69308cd416d80c6.png)

**Comment by RSSxdev** [comment]
英文换行是一个样式问题，已更新。
布局问题我先考虑一下怎么修改。

**Comment by bu1** [comment]
想了一下，布局问题我觉得可能有个更简单的解法，可以参考一下：
1. 原有布局不变
2. 之前说的那个阅读页面顶部组件常驻
3. 在阅读页面顶部常驻组件中增加收起搜索栏按钮

**Comment by bu1** [comment]
参考方案二：
无意中看到一个博客，下滑自动隐藏，上滑显示。
感觉这个方案更优秀，不需要增加收起搜索栏按钮。
`https://www.savouer.com/`

**Comment by RSSxdev** [comment]
要涉及布局结构的目前都无法修改，涉及的改动太多。目前在UI上面只能做一些简单的修改。

已经修改分享收藏栏为固定，搜索栏暂时无法修改。
