### ISSUE TITLE
希望可以调节字体大小

### ISSUE THREAD

**Issue by ghost** [RSSxdev/Readdig#6]
字体大小刚需，排版样式也可以安排上

**Comment by buyixiucai** [comment]
岁数大了,眼花,希望能看大字体

**Comment by RSSxdev** [comment]
是需要全局的字体大小设置，还是只要正文的字体大小

**Comment by buyixiucai** [comment]
调节正文字体，谢谢

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: RSSx ***@***.***>
发送时间: Friday, November 18, 2022 11:11:10 AM
收件人: RSSxdev/Readdig ***@***.***>
抄送: buyixiucai ***@***.***>; Comment ***@***.***>
主题: Re: [RSSxdev/Readdig] 希望可以调节字体大小 (Issue #6)


Closed #6<https://github.com/RSSxdev/Readdig/issues/6> as completed.

―
